// command mode
KEYDEF(toggle_fullscreen, "F11")
KEYDEF(toggle_visual_block, "<Control>v")
KEYDEF2(move_backward_blank_word, "<Control>Left", "<Shift>b")
KEYDEF2(move_forward_blank_word, "<Control>Right", "<Shift>w")
KEYDEF(move_up_half_screen, "<Control>u")
KEYDEF(move_down_half_screen, "<Control>d")
KEYDEF(move_up_screen, "<Control>b")
KEYDEF(move_down_screen, "<Control>f")
KEYDEF2(move_backward_word, "<Shift>Left", "b")
KEYDEF2(move_forward_word, "<Shift>Right", "w")
KEYDEF3(exit_command_mode, "Escape", "q", "<Control>bracketleft")
KEYDEF2(move_left, "Left", "h")
KEYDEF2(move_right, "Right", "l")
KEYDEF2(move_up, "Up", "k")
KEYDEF2(move_down, "Down", "j")
KEYDEF(move_forward_end_word, "e")
KEYDEF(move_forward_end_blank_word, "<Shift>e")
KEYDEF2(move_to_start_of_line, "Home", "0")
KEYDEF2(move_to_end_of_line, "End", "dollar")
KEYDEF(move_first, "asciicircum")
KEYDEF(move_to_first_row, "g")
KEYDEF(move_to_last_row, "<Shift>g")
KEYDEF(move_to_top_row, "<Shift>h")
KEYDEF(move_to_middle_row, "<Shift>m")
KEYDEF(move_to_bottom_row, "<Shift>l")
KEYDEF(toggle_visual, "v")
KEYDEF(toggle_visual_line, "<Shift>v")
KEYDEF(copy_clipboard, "y")
KEYDEF(search, "slash")
KEYDEF(search_reverse, "question")
KEYDEF(find_next, "n")
KEYDEF(find_previous, "<Shift>n")
KEYDEF(find_url, "u")
KEYDEF(find_url_reverse, "<Shift>u")
KEYDEF(open_selection, "o")
KEYDEF(confirm, "Return")
KEYDEF(select_url, "x")
