// command mode
KEYDEF_DUP(toggle_fullscreen, "F11")
KEYDEF(move_backward_blank_word, "<Shift>b")
KEYDEF(move_forward_blank_word, "<Shift>w")
KEYDEF(move_up_half_screen, "<Control>u")
KEYDEF(move_down_half_screen, "<Control>d")
KEYDEF(move_up_screen, "<Control>b")
KEYDEF(move_down_screen, "<Control>f")
KEYDEF(move_backward_word, "b")
KEYDEF(move_forward_word, "w")
KEYDEF3(exit_command_mode, "Escape", "q", "<Control>bracketleft")
KEYDEF2(move_left, "Left", "h")
KEYDEF(move_left5, "<Control>Left")
KEYDEF(move_left10, "<Shift>Left")
KEYDEF2(move_right, "Right", "l")
KEYDEF(move_right5, "<Control>Right")
KEYDEF(move_right10, "<Shift>Right")
KEYDEF2(move_up, "Up", "k")
KEYDEF(move_up5, "<Control>Up")
KEYDEF(move_up10, "<Shift>Up")
KEYDEF2(move_down, "Down", "j")
KEYDEF(move_down5, "<Control>Down")
KEYDEF(move_down10, "<Shift>Down")
KEYDEF(move_forward_end_word, "e")
KEYDEF(move_forward_end_blank_word, "<Shift>e")
KEYDEF2(move_to_start_of_line, "Home", "0")
KEYDEF2(move_to_end_of_line, "End", "dollar")
KEYDEF(move_first, "asciicircum")
KEYDEF(move_to_first_row, "g")
KEYDEF(move_to_last_row, "<Shift>g")
KEYDEF(move_to_top_row, "<Shift>h")
KEYDEF(move_to_middle_row, "<Shift>m")
KEYDEF(move_to_bottom_row, "<Shift>l")
KEYDEF_DUP(scroll_up_screen, "<Control><Shift>Prior")
KEYDEF_DUP(scroll_up_half_screen, "<Shift>Prior")
KEYDEF0_DUP(scroll_up)
KEYDEF0_DUP(scroll_up5)
KEYDEF0_DUP(scroll_up10)
KEYDEF_DUP(scroll_down_screen, "<Control><Shift>Next")
KEYDEF_DUP(scroll_down_half_screen, "<Shift>Next")
KEYDEF0_DUP(scroll_down)
KEYDEF0_DUP(scroll_down5)
KEYDEF0_DUP(scroll_down10)
KEYDEF(enter_visual, "<Control>space")
KEYDEF(enter_visual_line, "<Alt>space")
KEYDEF(enter_visual_block, "<Shift>space")
KEYDEF(toggle_visual, "v")
KEYDEF(toggle_visual_line, "<Shift>v")
KEYDEF(toggle_visual_block, "<Control>v")
KEYDEF_DUP(copy_clipboard, "y")
KEYDEF(yank_clipboard, "<Control>w")
KEYDEF(search, "slash")
KEYDEF(search_reverse, "question")
KEYDEF(find_next, "n")
KEYDEF(find_previous, "<Shift>n")
KEYDEF_DUP(find_url, "u")
KEYDEF(find_url_reverse, "<Shift>u")
KEYDEF(open_selection, "o")
KEYDEF(confirm, "Return")
KEYDEF(select_url, "x")
